"""Add agent_profiles table and chat_sessions.profile_id

Revision ID: 591c1e8767df
Revises: d2e3f4a5b6c7
Create Date: 2026-04-28 14:47:16.568565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '591c1e8767df'
down_revision: Union[str, None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('system_prompt_append', sa.Text(), server_default='', nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('enabled_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_agent_profiles_user_name')
    )
    op.create_index('ix_agent_profiles_user_id', 'agent_profiles', ['user_id'], unique=False)
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_activity_logs_user_id', table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('chat_sessions', sa.Column('profile_id', sa.String(), nullable=True))
    op.drop_index('idx_chat_sessions_updated', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_index('ix_knowledge_stats_reference', table_name='knowledge_stats')
    op.drop_index('ix_knowledge_stats_retrieval', table_name='knowledge_stats')
    op.drop_index('ix_knowledge_stats_search', table_name='knowledge_stats')
    op.drop_index('idx_note_emb_abstract', table_name='note_embeddings', postgresql_ops={'abstract_vec': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index('idx_note_emb_title', table_name='note_embeddings', postgresql_ops={'title_vec': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint('note_embeddings_note_id_fkey', 'note_embeddings', type_='foreignkey')
    op.alter_column('notes', 'domains',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('notes', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('notes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'seed'::character varying"))
    op.alter_column('notes', 'confidence',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('notes', 'source_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_source_chunks_embedding', table_name='source_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_source_chunks_source_id'), 'source_chunks', ['source_id'], unique=False)
    op.drop_index('idx_source_emb_summary', table_name='source_embeddings', postgresql_ops={'summary_vec': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index('idx_source_emb_title', table_name='source_embeddings', postgresql_ops={'title_vec': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint('source_embeddings_source_id_fkey', 'source_embeddings', type_='foreignkey')
    op.alter_column('sources', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_memories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_user_memories_user_id', table_name='user_memories')
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.alter_column('user_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('user_settings_user_id_fkey', 'user_settings', type_='foreignkey')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('user_settings_user_id_fkey', 'user_settings', 'users', ['user_id'], ['id'])
    op.alter_column('user_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.create_index('idx_user_memories_user_id', 'user_memories', ['user_id'], unique=False)
    op.alter_column('user_memories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'ingested_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('source_embeddings_source_id_fkey', 'source_embeddings', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_source_emb_title', 'source_embeddings', ['title_vec'], unique=False, postgresql_ops={'title_vec': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('idx_source_emb_summary', 'source_embeddings', ['summary_vec'], unique=False, postgresql_ops={'summary_vec': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_source_chunks_source_id'), table_name='source_chunks')
    op.create_index('idx_source_chunks_embedding', 'source_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('notes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'source_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('notes', 'confidence',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('notes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'seed'::character varying"))
    op.alter_column('notes', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('notes', 'domains',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.create_foreign_key('note_embeddings_note_id_fkey', 'note_embeddings', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_note_emb_title', 'note_embeddings', ['title_vec'], unique=False, postgresql_ops={'title_vec': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('idx_note_emb_abstract', 'note_embeddings', ['abstract_vec'], unique=False, postgresql_ops={'abstract_vec': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_knowledge_stats_search', 'knowledge_stats', ['item_type', sa.text('search_count DESC')], unique=False)
    op.create_index('ix_knowledge_stats_retrieval', 'knowledge_stats', ['item_type', sa.text('retrieval_count DESC')], unique=False)
    op.create_index('ix_knowledge_stats_reference', 'knowledge_stats', ['item_type', sa.text('reference_count DESC')], unique=False)
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('idx_chat_sessions_updated', 'chat_sessions', ['updated_at'], unique=False)
    op.drop_column('chat_sessions', 'profile_id')
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.create_index('idx_activity_logs_user_id', 'activity_logs', ['user_id'], unique=False)
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_agent_profiles_user_id', table_name='agent_profiles')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
